import React, { useState, useEffect, useRef } from 'react';
import { useTheme } from '../../context/ThemeContext';
import { useShop } from '../../context/ShopContext';
import { exportToPdf } from '../../utils/pdfExport';
import { 
  Building2, Printer, Share2, TrendingUp, TrendingDown, 
  Users, AlertTriangle, CheckCircle2, DollarSign, Calendar, X, Sparkles, Download
} from 'lucide-react';

export function OwnerSummaryModal({ isOpen, onClose }) {
  const { isDark } = useTheme();
  const { activeShop } = useShop();

  const [date, setDate] = useState(new Date().toISOString().split('T')[0]);
  const [summary, setSummary] = useState(null);
  const [loading, setLoading] = useState(false);
  const [isExportingPdf, setIsExportingPdf] = useState(false);

  const printableRef = useRef(null);

  const fetchSummary = async (targetDate) => {
    if (!activeShop?.id) return;
    setLoading(true);
    try {
      const res = await fetch(`/api/reports/owner-summary?shopId=${activeShop.id}&date=${targetDate || date}`);
      const data = await res.json();
      setSummary(data);
    } catch (e) {
      console.error('Fetch owner summary error:', e);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    if (isOpen) {
      fetchSummary(date);
    }
  }, [isOpen, activeShop?.id, date]);

  const handleDownloadPdf = async () => {
    if (!printableRef.current) return;
    setIsExportingPdf(true);
    try {
      await exportToPdf(printableRef.current, `Owner_Day_Summary_${date}.pdf`);
    } catch (err) {
      console.error('Failed to export PDF:', err);
    } finally {
      setIsExportingPdf(false);
    }
  };

  const handlePrint = () => {
    window.print();
  };

  const sendOnWhatsApp = () => {
    if (!summary) return;
    const topItemsText = (summary.topItems || []).map((t, i) => `${i + 1}. ${t.item_name} (${t.qty_sold} sold - ₹${t.revenue})`).join('\n');
    const msg = `📊 *DAILY STORE BUSINESS SUMMARY*
🏪 *${summary.shop?.name || activeShop?.name}*
📅 Date: ${new Date(summary.date).toLocaleDateString('en-IN')}

💰 *Today's Revenue: ₹${(summary.sales?.total_sales || 0).toLocaleString('en-IN')}*
🧾 Invoices Count: ${summary.sales?.invoice_count || 0} Bills

💳 *Collection Breakdown:*
• Cash Collected: ₹${(summary.sales?.cash_collected || 0).toLocaleString('en-IN')}
• UPI / QR: ₹${(summary.sales?.upi_collected || 0).toLocaleString('en-IN')}
• Card: ₹${(summary.sales?.card_collected || 0).toLocaleString('en-IN')}
• Credit (Udhar): ₹${(summary.sales?.credit_issued || 0).toLocaleString('en-IN')}

📉 *Store Expenses Today: ₹${(summary.expenses?.total_expenses || 0).toLocaleString('en-IN')}*
💵 *Net Drawer Cash Flow: ₹${(summary.netCashFlow || 0).toLocaleString('en-IN')}*

🏆 *Top 5 Selling Items:*
${topItemsText || 'No sales recorded yet today.'}

👥 Staff Present Today: ${summary.staff?.present || 0} / ${summary.staff?.total || 0}
⚠️ Low Stock Alert: ${summary.lowStockCount || 0} Items below safety level

_Generated by KwikStore Pro Retail ERP_`;

    const phone = (activeShop?.phone || '').replace(/\D/g, '');
    const url = phone ? `https://wa.me/91${phone.slice(-10)}?text=${encodeURIComponent(msg)}` : `https://wa.me/?text=${encodeURIComponent(msg)}`;
    window.open(url, '_blank');
  };

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 backdrop-blur-sm p-4 overflow-y-auto">
      <div className={`w-full max-w-xl rounded-2xl border shadow-2xl overflow-hidden transition-all ${
        isDark ? 'bg-slate-900 border-slate-800 text-white' : 'bg-white border-slate-200 text-slate-900'
      }`}>
        {/* Header */}
        <div className={`p-4 border-b flex items-center justify-between ${
          isDark ? 'bg-slate-950/70 border-slate-800' : 'bg-slate-50 border-slate-200'
        }`}>
          <div className="flex items-center space-x-2.5">
            <div className="w-9 h-9 rounded-xl bg-gradient-to-tr from-brand-600 to-emerald-500 text-white flex items-center justify-center font-bold">
              <Sparkles className="w-5 h-5" />
            </div>
            <div>
              <h2 className="text-sm font-bold">Owner's Day-End Business Summary</h2>
              <p className="text-[11px] text-slate-400">Instant executive overview of sales, collections, expenses, and staff</p>
            </div>
          </div>
          <button onClick={onClose} className="p-1 rounded-lg hover:bg-slate-800 text-slate-400 hover:text-white">
            <X className="w-4 h-4" />
          </button>
        </div>

        <div className="p-5 space-y-4">
          {/* Date Selector */}
          <div className="flex items-center justify-between">
            <label className="text-xs font-bold text-slate-300">Select Date:</label>
            <input
              type="date"
              value={date}
              onChange={(e) => setDate(e.target.value)}
              className={`p-1.5 rounded-xl border text-xs font-mono outline-none ${
                isDark ? 'bg-slate-950 border-slate-800 text-white' : 'bg-slate-50 border-slate-200 text-slate-900'
              }`}
            />
          </div>

          {/* Printable Container */}
          <div 
            id="printable-owner-summary"
            ref={printableRef}
            className={`p-4 rounded-xl border space-y-3 font-mono text-xs ${
              isDark ? 'bg-slate-950/90 border-slate-800' : 'bg-slate-50 border-slate-200'
            }`}
          >
            {/* Header for print preview */}
            <div className="text-center border-b pb-2 space-y-0.5 border-slate-700/50">
              <div className="text-sm font-black font-sans tracking-tight">
                {activeShop?.name || 'KwikStore Pro'}
              </div>
              <div className="text-[10px] text-slate-400 font-sans">
                {activeShop?.city || ''} {activeShop?.phone ? `• Ph: ${activeShop.phone}` : ''} {activeShop?.gstin ? `• GSTIN: ${activeShop.gstin}` : ''}
              </div>
              <div className="text-[11px] font-bold text-emerald-400 font-sans pt-0.5">
                OWNER'S DAY-END SUMMARY • {date}
              </div>
            </div>

            {summary ? (
              <div className="space-y-3">
                {/* Main KPI Banner */}
                <div className="grid grid-cols-3 gap-2">
                  <div className={`p-2.5 rounded-xl border text-center ${isDark ? 'bg-slate-900 border-slate-800' : 'bg-white border-slate-300'}`}>
                    <div className="text-[9px] text-slate-400 font-sans font-bold uppercase">Total Revenue</div>
                    <div className="text-sm font-bold text-emerald-400 font-mono mt-0.5">
                      ₹{(summary.sales?.total_sales || 0).toLocaleString('en-IN')}
                    </div>
                    <div className="text-[9px] text-slate-500">{summary.sales?.invoice_count || 0} Bills</div>
                  </div>

                  <div className={`p-2.5 rounded-xl border text-center ${isDark ? 'bg-slate-900 border-slate-800' : 'bg-white border-slate-300'}`}>
                    <div className="text-[9px] text-slate-400 font-sans font-bold uppercase">Expenses</div>
                    <div className="text-sm font-bold text-rose-400 font-mono mt-0.5">
                      ₹{(summary.expenses?.total_expenses || 0).toLocaleString('en-IN')}
                    </div>
                    <div className="text-[9px] text-slate-500">{summary.expenses?.expense_count || 0} Entries</div>
                  </div>

                  <div className={`p-2.5 rounded-xl border text-center ${isDark ? 'bg-slate-900 border-slate-800' : 'bg-white border-slate-300'}`}>
                    <div className="text-[9px] text-slate-400 font-sans font-bold uppercase">Net Cash Inflow</div>
                    <div className="text-sm font-bold text-brand-400 font-mono mt-0.5">
                      ₹{(summary.netCashFlow || 0).toLocaleString('en-IN')}
                    </div>
                    <div className="text-[9px] text-slate-500">Drawer Balance</div>
                  </div>
                </div>

                {/* Collections Breakdown */}
                <div className={`p-3 rounded-xl border space-y-1 ${isDark ? 'bg-slate-900 border-slate-800' : 'bg-white border-slate-300'}`}>
                  <div className="text-[10px] font-bold text-slate-300 font-sans border-b border-slate-700/50 pb-1 flex justify-between">
                    <span>Payment Tender Breakdown</span>
                    <span>{new Date(summary.date).toLocaleDateString('en-IN')}</span>
                  </div>
                  <div className="flex justify-between text-slate-400 text-[11px]">
                    <span>Cash Collections:</span>
                    <span className="text-emerald-400 font-bold">₹{(summary.sales?.cash_collected || 0).toLocaleString('en-IN')}</span>
                  </div>
                  <div className="flex justify-between text-slate-400 text-[11px]">
                    <span>UPI / QR Collections:</span>
                    <span className="text-sky-400 font-bold">₹{(summary.sales?.upi_collected || 0).toLocaleString('en-IN')}</span>
                  </div>
                  <div className="flex justify-between text-slate-400 text-[11px]">
                    <span>Card / POS Collections:</span>
                    <span className="text-purple-400 font-bold">₹{(summary.sales?.card_collected || 0).toLocaleString('en-IN')}</span>
                  </div>
                  <div className="flex justify-between text-slate-400 text-[11px]">
                    <span>Credit (Udhar) Issued:</span>
                    <span className="text-rose-400 font-bold">₹{(summary.sales?.credit_issued || 0).toLocaleString('en-IN')}</span>
                  </div>
                </div>

                {/* Top 5 Products */}
                <div className={`p-3 rounded-xl border space-y-1 ${isDark ? 'bg-slate-900 border-slate-800' : 'bg-white border-slate-300'}`}>
                  <div className="text-[10px] font-bold text-slate-300 font-sans border-b border-slate-700/50 pb-1">
                    Top 5 Best-Selling Products Today
                  </div>
                  {(summary.topItems || []).map((it, idx) => (
                    <div key={idx} className="flex justify-between items-center text-slate-400 text-[11px]">
                      <span className="font-sans font-bold text-slate-300">{idx + 1}. {it.item_name}</span>
                      <span className="text-brand-400 font-bold">{it.qty_sold} sold (₹{it.revenue})</span>
                    </div>
                  ))}
                  {(summary.topItems || []).length === 0 && (
                    <div className="text-slate-500 font-sans text-center py-1 text-[11px]">No sales logged for this date.</div>
                  )}
                </div>

                {/* Staff & Low Stock Quick Footer */}
                <div className="grid grid-cols-2 gap-2 text-[10px]">
                  <div className={`p-2 rounded-xl border flex items-center justify-between ${isDark ? 'bg-slate-900 border-slate-800' : 'bg-white border-slate-300'}`}>
                    <span className="text-slate-400">Staff Attendance:</span>
                    <span className="font-bold text-emerald-400">{summary.staff?.present || 0} / {summary.staff?.total || 0} Present</span>
                  </div>
                  <div className={`p-2 rounded-xl border flex items-center justify-between ${isDark ? 'bg-slate-900 border-slate-800' : 'bg-white border-slate-300'}`}>
                    <span className="text-slate-400">Low Stock Alert:</span>
                    <span className={`font-bold ${summary.lowStockCount > 0 ? 'text-rose-400' : 'text-slate-400'}`}>
                      {summary.lowStockCount || 0} Products
                    </span>
                  </div>
                </div>
              </div>
            ) : (
              <div className="text-center py-6 text-slate-500 font-sans">
                {loading ? 'Loading day summary...' : 'No summary data found for this date.'}
              </div>
            )}
          </div>

          {/* Action Buttons */}
          <div className="flex space-x-2 pt-2">
            <button
              onClick={handlePrint}
              className="flex-1 py-2.5 rounded-xl bg-slate-800 hover:bg-slate-700 text-white text-xs font-bold flex items-center justify-center space-x-1.5 transition-all"
            >
              <Printer className="w-4 h-4 text-cyan-400" />
              <span>Print Day Summary</span>
            </button>
            <button
              onClick={handleDownloadPdf}
              disabled={isExportingPdf || !summary}
              className="px-4 py-2.5 rounded-xl bg-indigo-600 hover:bg-indigo-500 text-white text-xs font-bold shadow-lg shadow-indigo-600/20 flex items-center justify-center space-x-1.5 transition-all disabled:opacity-50"
            >
              <Download className="w-4 h-4" />
              <span>{isExportingPdf ? 'Exporting...' : 'PDF'}</span>
            </button>
            <button
              onClick={sendOnWhatsApp}
              className="flex-1 py-2.5 rounded-xl bg-emerald-600 hover:bg-emerald-500 text-white text-xs font-bold shadow-lg shadow-emerald-600/20 flex items-center justify-center space-x-1.5 transition-all"
            >
              <Share2 className="w-4 h-4" />
              <span>Share WhatsApp</span>
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}

